### ISSUE TITLE
How to zoom out from mobile phone camera? 

### ISSUE THREAD

**Issue by smiley486** [nimiq/qr-scanner#111] opened 2021-05-26 08:02 UTC
Now when I load, the camera is zoomed in alot
i would like to keep the zoom neutral

**Comment by danimoh** [comment] 2021-08-17 11:47
I couldn't reproduce this on my device.
Can you post additional information, like
- your device
- browser
- camera resolution
- a screenshot showing the camera stream and a normal photo for comparison?

Note that the newest release of this lib allows for choosing a specific camera, have a look at the demo.
Please test whether your device might have multiple rear cameras and by default a camera with built-in zoom is chosen.

Additionally note, that by default, the picture is cropped to a region around the center before scanning.
This behavior can be customized, see https://github.com/nimiq/qr-scanner#2-create-a-qrscanner-instance.

**Comment by danimoh** [comment] 2022-02-04 12:27
Closing this due to lack of an update.
The information stated above should help to mitigate this kind of issue, if anyone else is experiencing it.

**Closed by danimoh** 2022-02-04 12:27 UTC
