### ISSUE TITLE
Scanner error: timeout once using webpack

### ISSUE THREAD

**Issue by hoomb** [nimiq/qr-scanner#51] opened 2019-07-09 12:25 UTC
I'm using webpack on my Project and getting this error once I embed the QR Scanner:
```
Scanner error: timeout
(anonymous) @ app.708859c27050a514213f.js:113
Promise.then (async)
(anonymous) @ app.708859c27050a514213f.js:113
requestAnimationFrame (async)
_scanFrame @ app.708859c27050a514213f.js:113
_onPlay @ app.708859c27050a514213f.js:113
play (async)
_onCanPlay @ app.708859c27050a514213f.js:113
```

Hier is the Code that I'm using:

```
import QrScanner from 'qr-scanner';
import QrScannerWorkerPath from '!!file-loader!../../../node_modules/qr-scanner/qr-scanner-worker.min.js';

export default () => {
    const video = document.getElementById('qr-video');
    const camHasCamera = document.getElementById('cam-has-camera');
    const camQrResult = document.getElementById('cam-qr-result');
    const camQrResultTimestamp = document.getElementById('cam-qr-result-timestamp');

    function setResult(label, result) {
        label.textContent = result;
        camQrResultTimestamp.textContent = new Date().toString();
        label.style.color = 'teal';
        clearTimeout(label.highlightTimeout);
        label.highlightTimeout = setTimeout(() => label.style.color = 'inherit', 100);
    }

        QrScanner.WORKER_PATH = QrScannerWorkerPath;

        QrScanner.hasCamera().then(hasCamera => camHasCamera.textContent = hasCamera);

        const scanner = new QrScanner(video, result => setResult(camQrResult, result));
        scanner.start();
};

```

Any help is highly appreciated.

**Comment by mchonan1996** [comment] 2019-07-16 00:57
Hey did you find a fix for this? I'm coming across the same thing.

**Comment by hoomb** [comment] 2019-07-16 05:34
I have switched to https://github.com/cozmo/jsqr

**Comment by mchonan1996** [comment] 2019-07-16 06:01
Are you using iOS / Android? I tried jsqr however was getting `null` from all QR codes that I tried. And in their demo, I don't see a video feed, and the panel says "No QR code detected".

QR codes in JS suck haha

**Comment by hoomb** [comment] 2019-07-16 06:47
I could tested it on iOS successfully.

**Comment by koxu1996** [comment] 2019-07-21 06:06
I switched to cozmo/jsQR too.

**Comment by habibtalib** [comment] 2019-07-24 04:48
Im facing timeout on mobile browser too.. im using file upload instead of canvas.  any root caused it time out ?

**Comment by gushonorato** [comment] 2019-10-17 17:59
I had the same error and it was related to how I was loading the files in webpack. I've sent a pull request (https://github.com/nimiq/qr-scanner/pull/60) with a suggestion with a different setup that I think It'll work in most cases.

Please, try it and let me know if it works for your cases.

**Comment by danimoh** [comment] 2020-07-09 22:44
The readme now provides extended instructions on how to set this up in webpack with the `file-loader` or `raw-loader`.

Regarding mobile issues:
On mobile browsers / iOS, the video required setting `autoplay` and `playsinline` manually.
These are now set automatically.

As I can't reproduce the issues described here and no further information is provided, I'm closing this.
If you keep encountering this problem, please open a new issue.

**Closed by danimoh** 2020-07-09 22:44 UTC

**Comment by oivvio** [comment] 2021-09-02 04:13
I had this same problem with webpack. Setting the  `QrScanner.WORKER_PATH` to fetch the worker code separately fixed the problem. A little less "clean" than bundling the code with webpack, but it works. So something like this:
    
    QrScanner.WORKER_PATH = "/js/vendor/qr-scanner-worker.min.js";

And of course you then have make sure that qr-scanner-worker.min.js is available in the specified location.

**Comment by gcardacci** [comment] 2022-03-02 20:22
I had the same error with qr-scanner version 1.3.0 and Webpack version 5.69.1.

I updated the qr scanner library to version 1.4.1 and the QR reading worked correctly again
